// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231123023240_Second")]
    partial class Second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("Domain.Advising", b =>
                {
                    b.Property<string>("PrepId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("prepID");

                    b.Property<string>("StudentbasicStudentId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("studentbasic_studentID");

                    b.Property<string>("OrienE11")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("orienE11");

                    b.Property<string>("OrienT10")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("orienT10");

                    b.Property<int?>("PaAppNo")
                        .HasColumnType("int")
                        .HasColumnName("paAppNo");

                    b.Property<string>("PrepStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("prepStatus");

                    b.HasKey("PrepId", "StudentbasicStudentId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "StudentbasicStudentId" }, "fk_advising_studentbasic1");

                    b.HasIndex(new[] { "PrepId" }, "prepID_UNIQUE")
                        .IsUnique();

                    b.ToTable("advising");
                });

            modelBuilder.Entity("Domain.Studentbasic", b =>
                {
                    b.Property<string>("StudentId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("studentID");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("LegalFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("legalFirstName");

                    b.Property<string>("LegalLastName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("legalLastName");

                    b.Property<string>("PersonalEmail")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("personalEmail");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("phoneNumber");

                    b.Property<string>("PreferredFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("preferredFirstName");

                    b.Property<string>("Pronouns")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("pronouns");

                    b.Property<decimal?>("UciGpa")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("uciGPA");

                    b.HasKey("StudentId")
                        .HasName("PRIMARY");

                    b.ToTable("studentbasic");
                });

            modelBuilder.Entity("Domain.Studentdetail", b =>
                {
                    b.Property<string>("DetailId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("detailID");

                    b.Property<string>("StudentbasicStudentId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("studentbasic_studentID");

                    b.Property<sbyte?>("Asuci")
                        .HasColumnType("tinyint")
                        .HasColumnName("asuci");

                    b.Property<sbyte?>("Chc")
                        .HasColumnType("tinyint")
                        .HasColumnName("chc");

                    b.Property<string>("ConsentFormE11")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("consentFormE11");

                    b.Property<string>("ConsentFormT10")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("consentFormT10");

                    b.Property<string>("CvE11")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cvE11");

                    b.Property<string>("CvT10")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cvT10");

                    b.Property<short?>("GradYear")
                        .HasColumnType("year")
                        .HasColumnName("gradYear");

                    b.Property<string>("HighDegree")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("highDegree");

                    b.Property<sbyte?>("HonorProg")
                        .HasColumnType("tinyint")
                        .HasColumnName("honorProg");

                    b.Property<sbyte?>("Larc")
                        .HasColumnType("tinyint")
                        .HasColumnName("larc");

                    b.Property<decimal?>("LeadExpMon")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("leadExpMon");

                    b.Property<sbyte?>("LowIncome")
                        .HasColumnType("tinyint")
                        .HasColumnName("lowIncome");

                    b.Property<sbyte?>("Paa")
                        .HasColumnType("tinyint")
                        .HasColumnName("paa");

                    b.Property<sbyte?>("Pbk")
                        .HasColumnType("tinyint")
                        .HasColumnName("pbk");

                    b.Property<sbyte?>("Sage")
                        .HasColumnType("tinyint")
                        .HasColumnName("sage");

                    b.Property<decimal?>("ServeExpMon")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("serveExpMon");

                    b.Property<bool?>("TranStu")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("tranStu");

                    b.Property<string>("TranscriptE11")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("transcriptE11");

                    b.Property<string>("TranscriptT10")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("transcriptT10");

                    b.Property<sbyte?>("Urop")
                        .HasColumnType("tinyint")
                        .HasColumnName("urop");

                    b.Property<sbyte?>("UsCitizen")
                        .HasColumnType("tinyint")
                        .HasColumnName("usCitizen");

                    b.Property<sbyte?>("Ushp")
                        .HasColumnType("tinyint")
                        .HasColumnName("ushp");

                    b.Property<sbyte?>("Veteran")
                        .HasColumnType("tinyint")
                        .HasColumnName("veteran");

                    b.HasKey("DetailId", "StudentbasicStudentId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "DetailId" }, "detailId_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "StudentbasicStudentId" }, "fk_studentdetail_studentbasic1");

                    b.ToTable("studentdetail");
                });

            modelBuilder.Entity("Domain.Advising", b =>
                {
                    b.HasOne("Domain.Studentbasic", "StudentbasicStudent")
                        .WithMany("Advisings")
                        .HasForeignKey("StudentbasicStudentId")
                        .IsRequired()
                        .HasConstraintName("fk_advising_studentbasic1");

                    b.Navigation("StudentbasicStudent");
                });

            modelBuilder.Entity("Domain.Studentdetail", b =>
                {
                    b.HasOne("Domain.Studentbasic", "StudentbasicStudent")
                        .WithMany("Studentdetails")
                        .HasForeignKey("StudentbasicStudentId")
                        .IsRequired()
                        .HasConstraintName("fk_studentdetail_studentbasic1");

                    b.Navigation("StudentbasicStudent");
                });

            modelBuilder.Entity("Domain.Studentbasic", b =>
                {
                    b.Navigation("Advisings");

                    b.Navigation("Studentdetails");
                });
#pragma warning restore 612, 618
        }
    }
}
